spring.application.name=Hambur-Besa

# Configuración de Conexión PostgreSQL (Neon DB)
spring.datasource.url=jdbc:postgresql://ep-nameless-wind-ax9t847a-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RfTs1FSnQP0J
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Configuración de JWT
app.security.jwt.secret=Ac7yFmX6ZQaroxkbbBZIOPkU/dn2bw+OXBJTQNq0QvN1HDkqKBkTLXrz/fVUx/LEy/yWr+jJcJK/Y7lTpyUs9w==
app.security.jwt.expiration=86400
